[package]
name = "playbook_web"
version = "0.1.0"
edition.workspace = true
publish = false

[dependencies]
axum.workspace = true
base64.workspace = true
ev_lib_classes.workspace = true
getrandom.workspace = true
regex.workspace = true
regex-syntax.workspace = true
reqwest.workspace = true
rmcp.workspace = true
rusqlite.workspace = true
sa_auth.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
tailwind_fuse.workspace = true
tokio.workspace = true

[build-dependencies]
ev_lib_classes.workspace = true
sha2.workspace = true

[dev-dependencies]
insta.workspace = true
rmcp = { workspace = true, features = ["client", "transport-streamable-http-client-reqwest", "reqwest"] }
